import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  dialog: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: 'column',
    zIndex: 999,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  headerBtn: { padding: 4 },
  headerTitle: { color: '#fff', fontSize: 12, fontWeight: 'bold', letterSpacing: 1 },

  body: {
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: 24,
    paddingBottom: 24,
    gap: 32,
  },

  /* Left column */
  left: {
    flex: 3,
    justifyContent: 'flex-start',
    paddingTop: 8,
    gap: 12,
    alignSelf: 'center',
  },
  cover: {
    width: '100%' as any,
    aspectRatio: 1,
    maxWidth: 400,
    alignSelf: 'center',
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  coverVideoMode: {
    aspectRatio: 16 / 9,
    maxWidth: 520,
  },
  coverImage: {
    width: '100%' as any,
    height: '100%' as any,
    resizeMode: 'cover',
  },
  backgroundImage: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.45,
    transform: [{ scale: 1.12 }],
  },
  backgroundOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  videoLoading: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  fullscreenBtn: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    width: 30,
    height: 30,
    borderRadius: 6,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  songInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  songInfoText: { flex: 1, overflow: 'hidden' },
  title: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  artist: { color: '#b3b3b3', fontSize: 14, marginTop: 2 },

  progressSection: { gap: 6 },
  progressTrack: {
    height: 28,
    justifyContent: 'center',
    position: 'relative',
  },
  progressBg: {
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 2,
  },
  progressFill: {
    position: 'absolute',
    height: 4,
    backgroundColor: '#fff',
    borderRadius: 2,
  },
  progressDot: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#fff',
    marginTop: -4,
    top: '50%',
  },
  timeRow: { flexDirection: 'row', justifyContent: 'space-between' },
  time: { color: '#b3b3b3', fontSize: 11 },

  controls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  playBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },

  footer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 16,
  },
  right: {
    flex: 2,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 20,
    overflow: 'hidden',
  },
  lyricsTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  lyricsTitle: {
    color: '#b3b3b3',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  lyricsSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: 12,
    height: 36,
  },
  lyricsSearchInput: {
    flex: 1,
    color: '#fff',
    fontSize: 13,
    height: 36,
    // @ts-ignore web-only
    outlineStyle: 'solid',
    // @ts-ignore web-only
    outlineWidth: 0,
  },
  lyricsSearchBtn: {
    padding: 4,
  },
  lyricsCenter: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  lyricsEmpty: { color: '#b3b3b3', fontSize: 14 },
  lyricsScroll: { flex: 1 },
  lyricLine: {
    color: 'rgba(255,255,255,0.35)',
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 48,
  },
  lyricOriginalLine: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 18,
    marginTop: 6,
    marginBottom: 2,
  },
  lyricLineActive: {
    color: '#fff',
  },
  lyricPlain: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 16,
    lineHeight: 28,
  },
  lyricOriginalPlain: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 8,
  },
  translateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  translateRowBottom: {
    marginBottom: 14,
  },
  translatePickerLabel: {
    color: '#888',
    fontSize: 11,
    fontWeight: '600',
    minWidth: 20,
  },
  translateToggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    minWidth: 36,
  },
  translateToggleText: {
    color: '#b3b3b3',
    fontSize: 10,
    fontWeight: '600',
  },
  translateToggleTextActive: {
    color: '#2c5af3ff',
  },
});
